services:
  api:
    build: .
    ports:
       - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  
  db:
    image: pgvector/pgvector:pg17
    environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: booknest
    POSTGRES_DB: booknest
  volumes:
    - postgres_data:/var/lib/postgresql/data
  ports:
    - "5432:5432"

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"

volumes:
  postgres_data:
