ALTER TYPE PAYMENT_STATUS ADD VALUE IF NOT EXISTS 'REFUND_INITIATED';

ALTER TYPE ORDER_STATUS ADD VALUE IF NOT EXISTS 'FAILED';

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS cancellation_reason TEXT DEFAULT NULL;
